"""Rule-based fatigue baseline classifier for Vigil M2.

This module implements the heuristic rule-based ACTIVE / DROWSY / SLEEPING
classifier and sustained-fatigue alert controller specified for M2 Day 3 (D3).

CRITICAL CONSTRAINTS:
    - Canonical classes: ACTIVE=0, DROWSY=1, SLEEPING=2.
    - NEVER read, reference, or use sample ground-truth labels during prediction.
    - Default thresholds are PROVISIONAL pending empirical calibration on recorded data.
    - Missing features (unobserved face/landmarks) are handled explicitly without fabrication.
"""

from __future__ import annotations

from dataclasses import dataclass

from vigil.ml.baseline.config import BaselineConfig
from vigil.ml.data.schema import FatigueLabel, SampleRecord


@dataclass(frozen=True)
class BaselinePrediction:
    """Prediction result generated by the RuleBasedBaseline classifier.

    Attributes:
        label: Predicted FatigueLabel (ACTIVE, DROWSY, or SLEEPING).
        label_id: Integer class ID (0: ACTIVE, 1: DROWSY, 2: SLEEPING).
        reason: Explanatory rule trigger name for explainability and auditing.
        closure_duration_ms: Tracked continuous eye closure duration (ms).
        sustained_fatigue_ms: Tracked continuous duration in fatigue state (ms).
        alert_triggered: Whether the sustained-fatigue alert is activated.
        timestamp_ms: Session-relative timestamp (ms) of the processed sample.
        frame_index: Frame sequence index of the processed sample.
        is_provisional: Whether the prediction was generated using provisional thresholds.
    """

    label: FatigueLabel
    label_id: int
    reason: str
    closure_duration_ms: float
    sustained_fatigue_ms: float
    alert_triggered: bool
    timestamp_ms: float
    frame_index: int
    is_provisional: bool


class RuleBasedBaseline:
    """Heuristic rule-based fatigue classifier and sustained alert controller.

    Applies deterministic rules to ocular features (EAR, eye closure duration,
    blink duration, PERCLOS) to classify driver fatigue states.

    State Tracking:
        Tracks temporal continuous eye closure duration and sustained fatigue
        across sequential frames. Automatically resets state if a new session
        is encountered to prevent cross-session leakage.
    """

    def __init__(self, config: BaselineConfig | None = None) -> None:
        """Initialize the rule-based baseline.

        Args:
            config: Baseline configuration containing heuristic thresholds.
                Defaults to BaselineConfig() with provisional thresholds.
        """
        self.config = config if config is not None else BaselineConfig()
        self._closure_start_timestamp_ms: float | None = None
        self._fatigue_start_timestamp_ms: float | None = None
        self._last_session_id: str | None = None
        self._last_timestamp_ms: float | None = None

    def reset(self) -> None:
        """Reset temporal state counters (e.g. at the start of a session)."""
        self._closure_start_timestamp_ms = None
        self._fatigue_start_timestamp_ms = None
        self._last_session_id = None
        self._last_timestamp_ms = None

    def classify(self, sample: SampleRecord) -> BaselinePrediction:
        """Classify a single SampleRecord.

        IMPORTANT: This method strictly relies on observational features.
        It NEVER accesses sample.label or sample.label_id.

        Args:
            sample: The input SampleRecord to classify.

        Returns:
            A BaselinePrediction containing the predicted label, explanation reason,
            closure duration, sustained fatigue duration, and alert state.
        """
        # Session boundary check: reset temporal state if session changed to prevent leakage
        if self._last_session_id is not None and sample.session_id != self._last_session_id:
            self.reset()
        self._last_session_id = sample.session_id

        # Missing-feature policy: handle missing face / landmarks safely
        if not sample.face_detected or not sample.landmarks_valid:
            # Eye state is unobservable; reset temporal closure tracking
            self._closure_start_timestamp_ms = None
            if self.config.missing_feature_fallback == FatigueLabel.ACTIVE:
                self._fatigue_start_timestamp_ms = None

            return BaselinePrediction(
                label=self.config.missing_feature_fallback,
                label_id=int(self.config.missing_feature_fallback),
                reason="missing_features",
                closure_duration_ms=0.0,
                sustained_fatigue_ms=0.0,
                alert_triggered=False,
                timestamp_ms=sample.timestamp_ms,
                frame_index=sample.frame_index,
                is_provisional=self.config.is_provisional,
            )

        # 1. Evaluate instantaneous eye closure
        # Eye is considered closed if is_eye_closed is True or ear_avg is below threshold
        is_closed = (
            sample.is_eye_closed is True
            or (sample.ear_avg is not None and sample.ear_avg < self.config.ear_close_threshold)
        )

        if is_closed:
            if self._closure_start_timestamp_ms is None:
                self._closure_start_timestamp_ms = sample.timestamp_ms
            closure_duration_ms = max(0.0, sample.timestamp_ms - self._closure_start_timestamp_ms)
        else:
            self._closure_start_timestamp_ms = None
            closure_duration_ms = 0.0

        # 2. Hierarchical state classification
        predicted_label: FatigueLabel
        reason: str

        # Priority 1: Acute SLEEPING state
        if closure_duration_ms >= self.config.sleeping_closure_duration_ms:
            predicted_label = FatigueLabel.SLEEPING
            reason = "prolonged_closure_sleeping"
        elif (
            sample.perclos is not None
            and sample.perclos >= self.config.sleeping_perclos_threshold
        ):
            predicted_label = FatigueLabel.SLEEPING
            reason = "high_perclos_sleeping"

        # Priority 2: DROWSY state
        elif closure_duration_ms >= self.config.drowsy_closure_duration_ms:
            predicted_label = FatigueLabel.DROWSY
            reason = "prolonged_closure_drowsy"
        elif (
            sample.perclos is not None
            and sample.perclos >= self.config.drowsy_perclos_threshold
        ):
            predicted_label = FatigueLabel.DROWSY
            reason = "elevated_perclos_drowsy"
        elif (
            sample.blink_duration_ms is not None
            and sample.blink_duration_ms >= self.config.drowsy_blink_duration_ms
        ):
            predicted_label = FatigueLabel.DROWSY
            reason = "sluggish_blink_drowsy"

        # Priority 3: Normal ACTIVE state
        else:
            predicted_label = FatigueLabel.ACTIVE
            reason = "normal_alert"

        # 3. Sustained-fatigue alert controller
        alert_triggered = False
        sustained_fatigue_ms = 0.0

        if predicted_label in (FatigueLabel.DROWSY, FatigueLabel.SLEEPING):
            if self._fatigue_start_timestamp_ms is None:
                self._fatigue_start_timestamp_ms = sample.timestamp_ms
            sustained_fatigue_ms = max(
                0.0, sample.timestamp_ms - self._fatigue_start_timestamp_ms
            )

            # Trigger alert on immediate sleep or sustained fatigue exceeding alert window
            if (
                (self.config.immediate_sleep_alert and predicted_label == FatigueLabel.SLEEPING)
                or sustained_fatigue_ms >= self.config.alert_sustain_window_ms
            ):
                alert_triggered = True
        else:
            # Reset sustained fatigue timer when driver returns to ACTIVE
            self._fatigue_start_timestamp_ms = None
            sustained_fatigue_ms = 0.0
            alert_triggered = False

        self._last_timestamp_ms = sample.timestamp_ms

        return BaselinePrediction(
            label=predicted_label,
            label_id=int(predicted_label),
            reason=reason,
            closure_duration_ms=closure_duration_ms,
            sustained_fatigue_ms=sustained_fatigue_ms,
            alert_triggered=alert_triggered,
            timestamp_ms=sample.timestamp_ms,
            frame_index=sample.frame_index,
            is_provisional=self.config.is_provisional,
        )

    def classify_session(
        self, samples: list[SampleRecord]
    ) -> list[BaselinePrediction]:
        """Classify an entire sequence of samples from a session.

        Automatically resets internal temporal state before processing the session.

        Args:
            samples: Ordered list of SampleRecords.

        Returns:
            List of BaselinePrediction objects corresponding to each sample.
        """
        self.reset()
        predictions: list[BaselinePrediction] = []
        for sample in samples:
            predictions.append(self.classify(sample))
        return predictions
